# app.yaml = application config file
application: coe-dbms-8
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /design
  static_dir: design
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest